name = input("What is your name? ")
print(name)
color = input("What is your favorite color?  ")
animal = input("What is your favorite animal?  ")
print("{}, you like a {} {}!".format(name,color,animal))

name = input("what is your name? ")
print(name)
dish = input("what is your favorite dish? ")
drink = input("what is your favorite drink? ")
print("{}, you like a {} {}!".format(name,dish,drink))
